name: rdf_dart
description: Support for working with RDF (Resource Description Framework) data in Dart.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  meta: ^1.16.0
  uuid: ^4.5.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  oath: ^0.4.0
  test: ^1.24.0
