name: rdf_dart
description: Support for working with RDF (Resource Description Framework) data in Dart.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2
resolution: workspace

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  convert: ^3.1.2
  crypto: ^3.0.6
  decimal: ^3.2.1
  intl: ^0.20.2
  iri: 0.1.1
  meta: ^1.16.0
  uuid: ^4.5.1
  xsd: ^0.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  oath: ^0.4.0
  test: ^1.24.0
