name: punycode_codec
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2
resolution: workspace

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  benchmark_harness: ^2.3.1
  lints: ^5.0.0
  test: ^1.24.0
